Effects = {'msoAnimEffectAppear':	{'id':1, "Description":	"Appears",},
'msoAnimEffectArcUp':	{'id':47, "Description":	'Arcs Up',},
'msoAnimEffectAscend':	{'id':39, "Description":	'Ascends',},
'msoAnimEffectBlast':	{'id':64, "Description":	'Blasts',},
'msoAnimEffectBlinds':	{'id':3, "Description":	'Blinds',},
'msoAnimEffectBoldFlash':	{'id':63, "Description":	'Bold Flash',},
'msoAnimEffectBoldReveal':	{'id':65, "Description":	'Bold Reveals',},
'msoAnimEffectBoomerang':	{'id':25, "Description":	'Boomerangs',},
'msoAnimEffectBounce':	{'id':26, "Description":	'Bounce',},
'msoAnimEffectBox':	{'id':4, "Description":	'Box',},
'msoAnimEffectBrushOnColor':	{'id':66, "Description":	'Brush on Color',},
'msoAnimEffectBrushOnUnderline':	{'id':67, "Description":	'Brush on Underline',},
'msoAnimEffectCenterRevolve':	{'id':40, "Description":	'Center Revolves',},
'msoAnimEffectChangeFillColor':	{'id':54, "Description":	'FillColor Changes',},
'msoAnimEffectChangeFont':	{'id':55, "Description":	'Font Changes',},
'msoAnimEffectChangeFontColor':	{'id':56, "Description":	'Font Color Changes',},
'msoAnimEffectChangeFontSize':	{'id':57, "Description":	'Font Size Changes',},
'msoAnimEffectChangeFontStyle':	{'id':58, "Description":	'Font Style Changes',},
'msoAnimEffectChangeLineColor':	{'id':60, "Description":	'Line color Changes',},
'msoAnimEffectCheckerboard':	{'id':5, "Description":	'Checkerboard Effect',},
'msoAnimEffectCircle':	{'id':6, "Description":	'Circle',},
'msoAnimEffectColorBlend':	{'id':68, "Description":	'Color Bleeds',},
'msoAnimEffectColorReveal':	{'id':27, "Description":	'Color Revealed',},
'msoAnimEffectColorWave':	{'id':69, "Description":	'Color Wave',},
'msoAnimEffectComplementaryColor':	{'id':70, "Description":	'Complementary Color',},
'msoAnimEffectComplementaryColor2':	{'id':71, "Description":	'Complementary Color2',},
'msoAnimEffectContrastingColor':	{'id':72, "Description":	'Contrasting Color',},
'msoAnimEffectCrawl':	{'id':7, "Description":	'Crawl Effect',},
'msoAnimEffectCredits':	{'id':28, "Description":	'Credits Effect',},
'msoAnimEffectCustom':	{'id':0, "Description":	'Custom Effect',},
'msoAnimEffectDarken':	{'id':73, "Description":	'Darken Effect',},
'msoAnimEffectDesaturate':	{'id':74, "Description":	'Desaturate Effect',},
'msoAnimEffectDescend':	{'id':42, "Description":	'Descend Effect',},
'msoAnimEffectDiamond':	{'id':8, "Description":	'Diamond Effect',},
'msoAnimEffectDissolve':	{'id':9, "Description":	'Dissolve Effect',},
'msoAnimEffectEaseIn':	{'id':29, "Description":	'EaseIn Effect',},
'msoAnimEffectExpand':	{'id':50, "Description":	'Expand Effect',},
'msoAnimEffectFade':	{'id':10, "Description":	'Fade Effect',},
'msoAnimEffectFadedSwivel':	{'id':41, "Description":	'Faded Swivel Effect',},
'msoAnimEffectFadedZoom':	{'id':48, "Description":	'Faded Zoom Effect',},
'msoAnimEffectFlashBulb':	{'id':75, "Description":	'Flash Bulb Effect',},
'msoAnimEffectFlashOnce':	{'id':11, "Description":	'Flash Once',},
'msoAnimEffectFlicker':	{'id':76, "Description":	'Flicker Effect',},
'msoAnimEffectFlip':	{'id':51, "Description":	'Flip Effect',},
'msoAnimEffectFloat':	{'id':30, "Description":	'Float Effect',},
'msoAnimEffectFly':	{'id':2, "Description":	'Fly Effect',},
'msoAnimEffectFold':	{'id':53, "Description":	'Fold Effect',},
'msoAnimEffectGlide':	{'id':49, "Description":	'Glide Effect',},
'msoAnimEffectGrowAndTurn':	{'id':31, "Description":	'Grow and Turn Effect',},
'msoAnimEffectGrowShrink':	{'id':59, "Description":	'Grow and Shrink Effect',},
'msoAnimEffectGrowWithColor':	{'id':77, "Description":	'Grow with Color Effect',},
'msoAnimEffectLighten':	{'id':78, "Description":	'Lighten Effect',},
'msoAnimEffectLightSpeed':	{'id':32, "Description":	'Light Speed Effect',},
'msoAnimEffectMediaPause':	{'id':84, "Description":	'Media Pause Effect',},
'msoAnimEffectMediaPlay':	{'id':83, "Description":	'Media Play Effect',},
'msoAnimEffectMediaStop':	{'id':85, "Description":	'Media Stop Effect',},
'msoAnimEffectPath4PointStar':	{'id':101, "Description":	'Path4PointStar Effect',},
'msoAnimEffectPath5PointStar':	{'id':90, "Description":	'Path5PointStar Effect',},
'msoAnimEffectPath6PointStar':	{'id':96, "Description":	'Path6PointStar Effect',},
'msoAnimEffectPath8PointStar':	{'id':102, "Description":	'Path8PointStar Effect',},
'msoAnimEffectPathArcDown':	{'id':122, "Description":	'Moves on the Arc Down path',},
'msoAnimEffectPathArcLeft':	{'id':136, "Description":	'Moves on the Arc Left path',},
'msoAnimEffectPathArcRight':	{'id':143, "Description":	'Moves on the Arc Right Path',},
'msoAnimEffectPathArcUp':	{'id':129, "Description":	'Moves on the Arc Up path',},
'msoAnimEffectPathBean':	{'id':116, "Description":	'Moves on the Bean path',},
'msoAnimEffectPathBounceLeft':	{'id':126, "Description":	'Moves on the Bounce Left path',},
'msoAnimEffectPathBounceRight':	{'id':139, "Description":	'Moves on the Bounce Right path',},
'msoAnimEffectPathBuzzsaw':	{'id':110, "Description":	'Moves on the Buzzsaw path',},
'msoAnimEffectPathCircle':	{'id':86, "Description":	'Moves on a Circular Path',},
'msoAnimEffectPathCrescentMoon':	{'id':91, "Description":	'Moves on a Crescent Moon path',},
'msoAnimEffectPathCurvedSquare':	{'id':105, "Description":	'Moves on a CurvedSquare path',},
'msoAnimEffectPathCurvedX':	{'id':106, "Description":	'Moves on a Curved X path',},
'msoAnimEffectPathCurvyLeft':	{'id':133, "Description":	'Moves on a Curvy Left path',},
'msoAnimEffectPathCurvyRight':	{'id':146, "Description":	'Moves on a Curvy Right path',},
'msoAnimEffectPathCurvyStar':	{'id':108, "Description":	'Moves on a Curvy Star path',},
'msoAnimEffectPathDecayingWave':	{'id':145, "Description":	'Moves on a Decaying Wave path',},
'msoAnimEffectPathDiagonalDownRight':	{'id':134, "Description":	'Moves on a Diagonal Down-Right path',},
'msoAnimEffectPathDiagonalUpRight':	{'id':141, "Description":	'Moves on a Diagonal Up-Right path',},
'msoAnimEffectPathDiamond':	{'id':88, "Description":	'Moves on a Diamond path',},
'msoAnimEffectPathDown':	{'id':127, "Description":	'Moves on a Down path',},
'msoAnimEffectPathEqualTriangle':	{'id':98, "Description":	'Moves on a equilateral triangle path',},
'msoAnimEffectPathFigure8Four':	{'id':113, "Description":	'Moves on a Figure8Four path',},
'msoAnimEffectPathFootball':	{'id':97, "Description":	'Moves on a Football path',},
'msoAnimEffectPathFunnel':	{'id':137, "Description":	'Moves on a Funnel path',},
'msoAnimEffectPathHeart':	{'id':94, "Description":	'Moves on a Heart shape path',},
'msoAnimEffectPathHeartbeat':	{'id':130, "Description":	'Moves on a Heart Beat path',},
'msoAnimEffectPathHexagon':	{'id':89, "Description":	'Moves on a Hexagon path',},
'msoAnimEffectPathHorizontalFigure8':	{'id':111, "Description":	'Moves on a Horizontal Figure8 path',},
'msoAnimEffectPathInvertedSquare':	{'id':119, "Description":	'Moves on a Inverted Square path',},
'msoAnimEffectPathInvertedTriangle':	{'id':118, "Description":	'Moves on a Inverted Triangle path',},
'msoAnimEffectPathLeft':	{'id':120, "Description":	'Moves on a Left path',},
'msoAnimEffectPathLoopdeLoop':	{'id':109, "Description":	'Moves on a LoopdeLoop path',},
'msoAnimEffectPathNeutron':	{'id':114, "Description":	'Moves on a Neutron path',},
'msoAnimEffectPathOctagon':	{'id':95, "Description":	'Moves on a Octagon path',},
'msoAnimEffectPathParallelogram':	{'id':99, "Description":	'Moves on a Parallelogram path',},
'msoAnimEffectPathPeanut':	{'id':112, "Description":	'Moves on a Peanut path',},
'msoAnimEffectPathPentagon':	{'id':100, "Description":	'Moves on a Pentagon path',},
'msoAnimEffectPathPlus':	{'id':117, "Description":	'Moves on a Plus path',},
'msoAnimEffectPathPointyStar':	{'id':104, "Description":	'Moves on a PointyStar path',},
'msoAnimEffectPathRight':	{'id':149, "Description":	'Moves on a Right path',},
'msoAnimEffectPathRightTriangle':	{'id':87, "Description":	'Moves on a RightTriangle path',},
'msoAnimEffectPathSCurve1':	{'id':144, "Description":	'Moves on a SCurve1 path',},
'msoAnimEffectPathSCurve2':	{'id':124, "Description":	'Moves on a SCurve2 path',},
'msoAnimEffectPathSineWave':	{'id':125, "Description":	'Moves on a SineWave path',},
'msoAnimEffectPathSpiralLeft':	{'id':140, "Description":	'Moves on a SpiralLeft path',},
'msoAnimEffectPathSpiralRight':	{'id':131, "Description":	'Moves on a SpiralRight path',},
'msoAnimEffectPathSpring':	{'id':138, "Description":	'Moves on a Spring path',},
'msoAnimEffectPathSquare':	{'id':92, "Description":	'Moves on a Square path',},
'msoAnimEffectPathStairsDown':	{'id':147, "Description":	'Moves on a StairsDown path',},
'msoAnimEffectPathSwoosh':	{'id':115, "Description":	'Moves on a Swoosh path',},
'msoAnimEffectPathTeardrop':	{'id':103, "Description":	'Moves on a Teardrop path',},
'msoAnimEffectPathTrapezoid':	{'id':93, "Description":	'Moves on a Trapezoid path',},
'msoAnimEffectPathTurnDown':	{'id':135, "Description":	'Moves on a TurnDown path',},
'msoAnimEffectPathTurnRight':	{'id':121, "Description":	'Moves on a TurnRight path',},
'msoAnimEffectPathTurnUp':	{'id':128, "Description":	'Moves on a TurnUp path',},
'msoAnimEffectPathTurnUpRight':	{'id':142, "Description":	'Moves on a TurnUpRight path',},
'msoAnimEffectPathUp':	{'id':148, "Description":	'Moves on an Up path',},
'msoAnimEffectPathVerticalFigure8':	{'id':107, "Description":	'Moves on a VerticalFigure8 path',},
'msoAnimEffectPathWave':	{'id':132, "Description":	'Moves on a Wave path',},
'msoAnimEffectPathZigzag':	{'id':123, "Description":	'Moves on a Zigzag path',},
'msoAnimEffectPeek':	{'id':12, "Description":	'Peek effect',},
'msoAnimEffectPinwheel':	{'id':33, "Description":	'Pinwel effect',},
'msoAnimEffectPlus':	{'id':13, "Description":	'Plus effect',},
'msoAnimEffectRandomBars':	{'id':14, "Description":	'Random Bars effect',},
'msoAnimEffectRandomEffects':	{'id':24, "Description":	'Random effects',},
'msoAnimEffectRiseUp':	{'id':34, "Description":	'Rise Up effect',},
'msoAnimEffectShimmer':	{'id':52, "Description":	'Shimmer effect',},
'msoAnimEffectSling':	{'id':43, "Description":	'Sling effect',},
'msoAnimEffectSpin':	{'id':61, "Description":	'Spin effect',},
'msoAnimEffectSpinner':	{'id':44, "Description":	'Spinner effect',},
'msoAnimEffectSpiral':	{'id':15, "Description":	'Spiral effect',},
'msoAnimEffectSplit':	{'id':16, "Description":	'Split effect',},
'msoAnimEffectStretch':	{'id':17, "Description":	'Stretch effect',},
'msoAnimEffectStretchy':	{'id':45, "Description":	'Stretchy effect',},
'msoAnimEffectStrips':	{'id':18, "Description":	'Strips effect',},
'msoAnimEffectStyleEmphasis':	{'id':79, "Description":	'Emphasis effect',},
'msoAnimEffectSwish':	{'id':35, "Description":	'Swish effect',},
'msoAnimEffectSwivel':	{'id':19, "Description":	'Swivel effect',},
'msoAnimEffectTeeter':	{'id':80, "Description":	'Teeter effect',},
'msoAnimEffectThinLine':	{'id':36, "Description":	'Thin line effect',},
'msoAnimEffectTransparency':	{'id':62, "Description":	'Transparency effect',},
'msoAnimEffectUnfold':	{'id':37, "Description":	'Unfold effect',},
'msoAnimEffectVerticalGrow':	{'id':81, "Description":	'Vertical Grow effect',},
'msoAnimEffectWave':	{'id':82, "Description":	'Wave effect',},
'msoAnimEffectWedge':	{'id':20, "Description":	'Wedge effect',},
'msoAnimEffectWheel':	{'id':21, "Description":	'Wheel effect',},
'msoAnimEffectWhip':	{'id':38, "Description":	'Whip effect',},
'msoAnimEffectWipe':	{'id':22, "Description":	'Wipe effect',},
'msoAnimEffectZip':	{'id':46, "Description":	'Zip effect',},
'msoAnimEffectZoom':	{'id':23, "Description":	'Zoom effect',},
}

